### ISSUE TITLE
422 error (star-chart)

### ISSUE THREAD

**Issue by DowneyX** [AstronomyAPI/Documentation#7]
i can't get the star-chart to work,
```js
$.ajax({
            type: 'Post',
            url: 'https://api.astronomyapi.com/api/v2/studio/star-chart',
            dataType: 'json',
            headers: {
                "Authorization": "Basic " + hash,
            },
            data: {
                "style": "inverted",
                "observer": {
                    "latitude": 33.775867,
                    "longitude": -84.39733,
                    "date": "2019-12-20",
                },
                "view": {
                    "type": "constellation",
                    "parameters": {
                        "constellation": "ori", // 3 letter constellation id
                    },
                },
            },
            success: function (data) {
                console.log(data);
            }
        })
```

this is my code but i keep getting a 422 statusCode.

![image](https://user-images.githubusercontent.com/57352505/100022058-d091b180-2de2-11eb-9754-9ed0417a8066.png)

im i doing something wrong?

**Comment by astroanu** [comment]
Hi, on jquery ajax, you need use JSON.stringify, it should work

`  data: JSON.stringify({
    "style": "inverted",
    "observer": {
      "latitude": 33.775867,
      "longitude": -84.39733,
      "date": "2019-12-20",
    },
    "view": {
      "type": "constellation",
      "parameters": {
        "constellation": "ori", // 3 letter constellation id
      },
    },
  }),`

**Comment by DowneyX** [comment]
thank you so much for the reply,
it works now. 
thank you.
