### ISSUE TITLE
Using API with python

### ISSUE THREAD

**Issue by AdvaithGS** [AstronomyAPI/Documentation#9]
Hey there, 
I'm looking to use this API with python but so far im unable to get past the authorization, ive tried many ways to do it in accordance to the instructions but i just cant seem to be able to access it.
If it doesnt inconvenience you, please share how it can be done in Python.

Thanking you,
Advaith GS
( I hope my regular pestering doesnt bother you :)  )

**Comment by astroanu** [comment]
Hi, not sure why it didn't work for you, but here's an example
 
        import requests
        from requests.auth import HTTPBasicAuth
        
        response = requests.get("https://api.astronomyapi.com/api/v2/bodies", auth=HTTPBasicAuth('appid', 'secret'))
        
        
        print(response.json())

**Comment by AdvaithGS** [comment]
So i tried to use your with moon-phase function but its not working. It is working with  https://api.astronomyapi.com/api/v2/bodies thought.

**Comment by AdvaithGS** [comment]
So i tried using a post method and now im getting a 422 error, i think it is because im not able to specify parameters, any method to do that? The python dictionary does not work.

**Comment by AdvaithGS** [comment]
Never mind I just found the solution after trying a different ways with POST. Thanks a lot!
